name: '@jagreehal/todo-cli CI/CD'

on:
  push:
    paths:
      - 'packages/todo-cli/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Extract version
        id: pkg
        run: echo "::set-output name=version::$(cd packages/todo-cli && node -p "require('./package.json').version")"

      - name: Package Binaries with Execution Permissions
        run: |
          chmod +x ./clis/todo-cli-linux-x64
          chmod +x ./clis/todo-cli-macos-x64
          chmod +x ./clis/todo-cli-macos-arm64
          tar -czvf todo-cli-linux-x64.tar.gz -C packages/todo-cli/clis todo-cli-linux-x64
          tar -czvf todo-cli-macos-x64.tar.gz -C packages/todo-cli/clis todo-cli-macos-x64
          tar -czvf todo-cli-macos-arm64.tar.gz -C packages/todo-cli/clis todo-cli-macos-arm64
          mv ./clis/todo-cli-win-x64.exe packages/todo-cli/todo-cli-win-x64.exe  # move the .exe file out of the clis directory to avoid it being tarred

      - name: Deploy to S3
        run: |
          aws s3 cp todo-cli-linux-x64.tar.gz s3://todo-dev-tooling/clis/${{ steps.pkg.outputs.version }}/
          aws s3 cp todo-cli-macos-x64.tar.gz s3://todo-dev-tooling/clis/${{ steps.pkg.outputs.version }}/
          aws s3 cp todo-cli-macos-arm64.tar.gz s3://todo-dev-tooling/clis/${{ steps.pkg.outputs.version }}/
          aws s3 cp todo-cli-win-x64.exe s3://todo-dev-tooling/clis/${{ steps.pkg.outputs.version }}/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
